# Generated by Django 4.2.4 on 2023-08-21 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importer",
            name="lic_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 21, 15, 26, 1, 445913, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
