# Generated by Django 4.2.4 on 2023-08-24 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_importer_bond_date_alter_importer_lic_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="importer",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importer",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="importer",
            name="bond_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 24, 18, 3, 8, 954806, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="lic_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 24, 18, 3, 8, 954806, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
