# Generated by Django 4.2.4 on 2023-08-26 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_importer_is_closed_importer_is_paused_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importer",
            name="bond_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 26, 14, 44, 59, 919324, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="lic_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 26, 14, 44, 59, 919324, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
